[package]
name = "sandboxed-function"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sandbox-generated = { path = "../rWasm/generated" }
macro-utils = { path = "./macro-utils" }

[profile.release]
panic = "abort"