[package]
name = "sandboxed-function"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sandbox-generated = { path = "../../generated" }

[profile.release]
panic = "abort"