#![no_std]
/// This is a wrapper around the transpiled Rust code generated by rWasm.
/// It exposes the necessary entrypoints for Dandelion.
/// The primary reason for the existance of this wrapper is the
///     #[no_mangle]
/// requirement for exposed symbols, which does not work with the
///    #![forbid(unsafe_code)]
/// requirement in the rWasm generated code.

// need to define a panic handler, since this is a cdylib
use core::panic::PanicInfo;
#[panic_handler]
fn panic(_info: &PanicInfo) -> ! {
    loop {}
}

extern crate macro_utils;
#[no_mangle]
pub static SYSTEM_DATA_WASM_MEM_OFFSET: i32 = macro_utils::get___dandelion_system_data!();
#[no_mangle]
pub static INTERFACE_MEM_SIZE_FOR_WASM: i32 = macro_utils::get_INTERFACE_MEM_SIZE_FOR_WASM!();
#[no_mangle]
pub static INTERFACE_MEM_FOR_WASM: i32 = macro_utils::get_INTERFACE_MEM_FOR_WASM!();

mod function_interface {
    use libc::{c_int, size_t, uintptr_t};

    #[repr(C)]
    pub struct DandelionSystemData {
        exit_code: c_int,
        heap_begin: uintptr_t,
        heap_end: uintptr_t,
        input_sets_len: size_t,
        input_sets: *const IoSetInfo,
        output_sets_len: size_t,
        output_sets: *const IoSetInfo,
        input_bufs: *const IoBufferDescriptor,
        output_bufs: *const IoBufferDescriptor,
    }

    #[repr(C)]
    pub struct IoSetInfo {
        ident: uintptr_t,
        ident_len: size_t,
        offset: size_t,
    }

    #[repr(C)]
    pub struct IoBufferDescriptor {
        ident: uintptr_t,
        ident_len: size_t,
        data: uintptr_t,
        data_len: size_t,
        key: size_t,
    }

    extern "C" {
        pub static mut SYSTEM_DATA_PTR: *mut DandelionSystemData;
    }
}

mod wrapper {
    extern crate sandbox_generated;
    use sandbox_generated as Generated;

    pub struct __WasmModule {
        pub module: Generated::WasmModule,
    }

    impl __WasmModule {
        #[no_mangle]
        pub fn new() -> Self {
            Self {
                module: Generated::WasmModule::new(),
            }
        }
        #[no_mangle]
        #[allow(non_snake_case)]
        pub fn get___system_data(&self) -> Option<i32> {
            self.module.get___dandelion_system_data()
        }
        #[no_mangle]
        #[allow(non_snake_case)]
        pub fn alloc(&mut self, size: i32, alignment: i32) -> i32 {
            self.module.dandelion_alloc(size, alignment).unwrap()
        }
    }
}

#[no_mangle]
pub unsafe fn _start() -> i32 {
    let mut module = wrapper::__WasmModule::new();
    // check that we received system data from the host
    match function_interface::SYSTEM_DATA_PTR as i32 {
        0 => return -2,
        _ => ()
    };
    // let interface_mem_size = module.module.get_INTERFACE_MEM_SIZE_FOR_WASM().unwrap();
    // let interface_mem_base = module.module.get_INTERFACE_MEM_FOR_WASM().unwrap();
    match module.module._start() {
        Some(_) => 0,
        None => -1,
    }
}