[package]
name = "macro-utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["proc-macro"]

[dependencies]
proc-macro2 = "1.0.86"
syn = "2.0.38"
sandbox-generated = { path = "../../rWasm/generated" }
konst = "0.3.6"